spring:
  application:
    name: devhands

openapi:
  product:
    base-path: ""

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO