spring:
  application:
    name: devhands
  flyway:
    schemas:
      - public
      - product
  jpa:
    show-sql: true

openapi:
  product:
    base-path: ""

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    sql: INFO
    root: INFO
    org.springframework: INFO

server:
  port: 8080
