spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - product
  jpa:
    show-sql: true

server:
  port: 8080

logging:
  level:
    sql: info