###

GET http://localhost:8080/actuator

###

GET http://localhost:8080/swagger-ui

###
GET http://localhost:8080/catalogue-api/v0/products


###
GET http://92.118.113.155:8080/catalogue-api/v0/products


###
POST http://localhost:8080/catalogue-api/v0/products
Content-Type: application/json

{
  "title": "Tomato",
  "description": "Red"
}

###
PUT http://localhost:8080/catalogue-api/v0/products
Content-Type: application/json

{
  "title": "",
  "description": ""
}

###
GET http://localhost:8080/catalogue-api/v0/products/{{productId}}

###
DELETE http://localhost:8080/catalogue-api/v0/products/{{productId}}