###
GET http://localhost:8080/product-api/v0/products

###
POST http://localhost:8080/product-api/v0/products
Content-Type: application/json

{
  "title": "Tomato",
  "description": "Red"
}

###
PUT http://localhost:8080/product-api/v0/products
Content-Type: application/json

{
  "id": 2,
  "title": "New title",
  "description": "New Description"
}

###
GET http://localhost:8080/product-api/v0/products/2

###
DELETE http://localhost:8080/product-api/v0/products/1



###
GET http://localhost:8080/actuator

###
GET http://localhost:8080/swagger-ui
